# Generated by Django 4.2.7 on 2026-02-02 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualite_service', models.BooleanField(default=False)),
                ('accueil_personnel', models.BooleanField(default=False)),
                ('rapidite', models.BooleanField(default=False)),
                ('rapport_qualite_prix', models.BooleanField(default=False)),
                ('satisfaction_globale', models.BooleanField(default=False)),
                ('suggestions', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
            },
        ),
    ]
