# Generated by Django 4.2.7 on 2026-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='accueil_personnel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='qualite_service',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='rapidite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='rapport_qualite_prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='satisfaction_globale',
            field=models.IntegerField(default=0),
        ),
    ]
