# Generated by Django 6.0.1 on 2026-02-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_avis_accueil_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='connu_amis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='connu_autres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='connu_autres_precision',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='avis',
            name='connu_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='connu_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='connu_tiktok',
            field=models.BooleanField(default=False),
        ),
    ]
