# Generated by Django 6.0.1 on 2026-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_avis_connu_amis_avis_connu_autres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='connu_amis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='connu_autres',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='connu_autres_precision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='connu_facebook',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='connu_instagram',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='connu_tiktok',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
